### ISSUE TITLE
JPEG画像以外のファイルのダウンロードであっても mimetype が image/jpeg として扱われる

### ISSUE THREAD

**Issue by cat-in-136** [diffshare/imgs#76]
JPEG画像以外（たとえば PNG 画像）を使った場合、正しく Firebase に暗号化アップロードされ、閲覧時にも正しく表示される。しかしながら「ダウンロード」では mimetype が image/jpeg として扱われ、ブラウザによってはファイル名のデフォルトは ◯◯.jpg となるなどの影響がある。

回避策：その場合であってもファイルの中身はオリジナルの PNG 画像のままでありファイル名を手動で書き換えることで対処は可能

原因はアップロードされる画像ファイルが jpeg ファイルしか考慮されておらず、ダウンロードリンクを生成するときの blob において image/jpeg が決め打ちとなっていること。https://github.com/diffshare/imgs/blob/b2a832dd55a3bc36c252b1d9e9eb23aa2e82050d/angular/src/app/model/decrypted-image.ts#L10-L17

具体的には `DecryptedImage` で `new Blob()` するときに mime type が image/jpeg 固定となっているが、ここで `dec: ArrayBuffer` の先頭バイトを確認して適切な mime type にするようなコードが好ましいと思われる。

**Comment by diffshare** [comment]
この問題は、[porting-to-next-js branch](https://github.com/diffshare/imgs/tree/porting-to-next-js)で一括して対応中です。

以下の指摘が来ています。

以下の箇所に注目が必要です：
- [decrypted-image.ts#L16](https://github.com/diffshare/imgs/blob/5305e5cb314fd9b4d3b88ac2d0ee56083265fa6a/src/lib/decrypted-image.ts#L16)
- [decrypted-image.ts#L120](https://github.com/diffshare/imgs/blob/5305e5cb314fd9b4d3b88ac2d0ee56083265fa6a/src/lib/decrypted-image.ts#L120)

復号時のBlobのmimetypeがJPEGのままとなっています。これは問題で、なぜなら `<a>` 要素の `download` 属性が設定されていない場合、ブラウザはBlobのmimetypeを参照してファイル名を決定します。しかし、現状ではそのmimetypeが `jfif` や `jpg` などとなってしまっています。
